// vuejs/src/page/ComponentCon.vue
<template>
  <div>
    <h3>đây là con Con</h3>
    <ul>
      <li v-for="item in materialList" :key="item.id">
        <label>
          <input
            type="checkbox"
            :checked="selectedIds.includes(item.id)"
            @change="handleCheckboxChange(item)"
          />
          {{ item.material_num }} - {{ item.material_desc }} ({{ item.uom }})
        </label>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  props: {
    materialList: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
      selectedIds: [],
    };
  },
  methods: {
    handleCheckboxChange(item) {
      const index = this.selectedIds.indexOf(item.id);
      if (index > -1) {
        this.selectedIds.splice(index, 1); // Bỏ chọn
      } else {
        this.selectedIds.push(item.id); // Chọn thêm
      }

      // Lấy danh sách item được chọn
      const selectedItems = this.materialList.filter((m) => this.selectedIds.includes(m.id));

      // Emit danh sách đã chọn về cha
      this.$emit("selection-change", selectedItems);
    },
  },
};
</script>

// reactjsdemo/src/passdata/componentCon.jsx
import React, { useState } from "react";

function ComponentCon({ materialList, onSelectionChange }) {
  const [selectedIds, setSelectedIds] = useState([]);

  const handleCheckboxChange = (item) => {
    let updatedSelected;

    if (selectedIds.includes(item.id)) {
      // Bỏ chọn
      updatedSelected = selectedIds.filter((id) => id !== item.id);
    } else {
      // Thêm chọn
      updatedSelected = [...selectedIds, item.id];
    }

    setSelectedIds(updatedSelected);

    // Gửi danh sách item đã chọn (dựa trên ID)
    const selectedItems = materialList.filter((m) => updatedSelected.includes(m.id));
    onSelectionChange(selectedItems);
  };

  return (
    <div>
      <h3>Con</h3>
      <ul>
        {materialList.map((item) => (
          <li key={item.id}>
            <label>
              <input
                type="checkbox"
                checked={selectedIds.includes(item.id)}
                onChange={() => handleCheckboxChange(item)}
              />
              {item.material_num} - {item.material_desc} ({item.uom})
            </label>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default ComponentCon;
